// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Documents/JAVA/JFLEXG/src/JFlex.flex



@SuppressWarnings("fallthrough")
public class Yylex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\2\1\1\2\2\3\1\4\22\0\1\1\1\0"+
    "\1\5\2\0\1\6\1\7\1\0\2\7\1\10\1\11"+
    "\1\7\1\12\1\7\1\13\12\14\2\7\1\15\1\16"+
    "\1\17\2\0\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\31\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\7\1\51\1\7\1\0"+
    "\1\52\1\0\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\31\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\3\7\7\0\1\3\252\0"+
    "\2\53\115\0\1\54\u01a8\0\2\3\u0100\0\1\55\325\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\1\1\3\1\4\4\3\1\5"+
    "\2\4\21\6\2\1\1\2\1\0\1\7\1\0\1\10"+
    "\2\0\2\6\1\0\10\6\1\4\6\6\1\0\1\6"+
    "\1\4\22\6\11\0\1\6\1\0\1\6\1\0\4\6"+
    "\1\0\11\6\1\0\3\6\1\4\1\6\1\0\5\6"+
    "\1\0\7\6\1\0\3\6\1\0\3\6\1\0\1\6"+
    "\2\0\1\4\7\0\1\6\1\0\6\6\1\0\3\6"+
    "\1\0\4\6\1\0\1\6\1\0\1\6\1\0\3\6"+
    "\2\0\3\6\2\0\4\6\7\0\1\6\1\0\1\6"+
    "\1\11\1\6\1\0\2\6\2\4\4\6\1\0\1\6"+
    "\1\0\2\6\2\0\1\6\1\0\2\6\2\0\1\6"+
    "\1\4\1\6\5\0\1\6\1\0\1\6\1\0\1\6"+
    "\1\0\3\6\1\0\2\6\1\0\1\6\1\0\2\6"+
    "\5\0\3\6\1\0\1\6\1\11\1\6\1\0\2\6"+
    "\4\0\2\6\1\0\1\6\2\0\1\6\1\0\1\6"+
    "\2\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[272];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\56\0\134\0\212\0\270\0\56\0\56"+
    "\0\346\0\u0114\0\u0142\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228"+
    "\0\u0256\0\u0284\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a\0\u0398"+
    "\0\u03c6\0\u03f4\0\u0422\0\u0450\0\u047e\0\u04ac\0\u04da\0\u0508"+
    "\0\u0536\0\u0564\0\56\0\270\0\56\0\u0592\0\56\0\u05c0"+
    "\0\u05ee\0\u061c\0\u064a\0\u0678\0\u06a6\0\u06d4\0\u0702\0\u0730"+
    "\0\u075e\0\u078c\0\u07ba\0\u07e8\0\u0816\0\u0844\0\u0872\0\u08a0"+
    "\0\u08ce\0\u08fc\0\u092a\0\u0958\0\u0986\0\u036a\0\u09b4\0\u09e2"+
    "\0\u0a10\0\u0a3e\0\u0a6c\0\u0a9a\0\u0ac8\0\u0af6\0\u0b24\0\u0b52"+
    "\0\u0b80\0\u0bae\0\u0bdc\0\u0c0a\0\u0c38\0\u0c66\0\u0c94\0\u0cc2"+
    "\0\u0cf0\0\u0d1e\0\u0d4c\0\u0d7a\0\u0da8\0\u0dd6\0\u0e04\0\u0e32"+
    "\0\u0e60\0\u0e8e\0\u0ebc\0\u0eea\0\u0f18\0\u0f46\0\u0f74\0\u0fa2"+
    "\0\u0fd0\0\u0ffe\0\u102c\0\u105a\0\u1088\0\u10b6\0\u10e4\0\u1112"+
    "\0\u1140\0\u116e\0\u119c\0\u11ca\0\u11f8\0\u1226\0\u1254\0\u1282"+
    "\0\u12b0\0\u12de\0\u130c\0\u133a\0\u1368\0\u1396\0\u13c4\0\u13f2"+
    "\0\u1420\0\u144e\0\u147c\0\u14aa\0\u14d8\0\u1506\0\u1534\0\u1562"+
    "\0\u1590\0\u15be\0\u15ec\0\u161a\0\u1648\0\u1676\0\u16a4\0\u16d2"+
    "\0\u1700\0\u172e\0\u175c\0\u178a\0\u17b8\0\u17e6\0\u1814\0\u1842"+
    "\0\u1870\0\u189e\0\u18cc\0\u18fa\0\u1928\0\u1956\0\u1984\0\u19b2"+
    "\0\u19e0\0\u1a0e\0\u1a3c\0\u1a6a\0\u1a98\0\u1ac6\0\u1af4\0\u1b22"+
    "\0\u1b50\0\u1b7e\0\u1bac\0\u1bda\0\u1c08\0\u1c36\0\u1c64\0\u1c92"+
    "\0\u1cc0\0\u1cee\0\u1d1c\0\u1d4a\0\u1d78\0\u1da6\0\u1dd4\0\u1e02"+
    "\0\u1e30\0\u1e5e\0\u1e8c\0\u1eba\0\u1ee8\0\u1f16\0\u1f44\0\u1f72"+
    "\0\u1fa0\0\u1fce\0\u1ffc\0\u202a\0\u2058\0\u2086\0\u20b4\0\u20e2"+
    "\0\u2110\0\u036a\0\u213e\0\u216c\0\u219a\0\u21c8\0\u21f6\0\u2224"+
    "\0\u2252\0\u2280\0\u22ae\0\u22dc\0\u230a\0\u2338\0\u2366\0\u2394"+
    "\0\u23c2\0\u23f0\0\u241e\0\u244c\0\u247a\0\u24a8\0\u24d6\0\u2504"+
    "\0\u2532\0\u2560\0\u15be\0\u258e\0\u25bc\0\u25ea\0\u2618\0\u2646"+
    "\0\u2674\0\u26a2\0\u26d0\0\u26fe\0\u272c\0\u275a\0\u2788\0\u27b6"+
    "\0\u27e4\0\u2812\0\u2840\0\u286e\0\u289c\0\u28ca\0\u28f8\0\u2926"+
    "\0\u2954\0\u2982\0\u29b0\0\u29de\0\u2a0c\0\u2a3a\0\u2a68\0\u2a96"+
    "\0\u2ac4\0\u2af2\0\u2b20\0\u2b4e\0\56\0\u2b7c\0\u2baa\0\u2bd8"+
    "\0\u2c06\0\u2c34\0\u2c62\0\u2c90\0\u2cbe\0\u2cec\0\u2d1a\0\u2d48"+
    "\0\u2d76\0\u2da4\0\u2dd2\0\u2e00\0\u2e2e\0\u2e5c\0\u2e8a\0\u2eb8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[272];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\10\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\2\27\1\31\1\27\1\32\1\27\1\33\1\34\1\35"+
    "\1\36\1\27\1\37\1\40\3\27\2\3\1\41\1\42"+
    "\1\3\57\0\2\4\55\0\1\43\53\0\2\44\1\0"+
    "\1\44\1\0\1\45\43\44\1\46\4\44\10\0\1\47"+
    "\56\0\1\47\56\0\1\47\53\0\1\50\2\0\1\51"+
    "\56\0\1\15\57\0\2\10\54\0\1\10\53\0\1\27"+
    "\3\0\1\27\1\52\17\27\1\53\7\27\1\0\1\27"+
    "\1\0\1\54\15\0\1\27\3\0\16\27\1\55\1\27"+
    "\1\56\6\27\1\57\1\27\1\0\1\27\17\0\1\27"+
    "\3\0\1\60\6\27\1\61\3\27\1\62\2\27\1\63"+
    "\12\27\1\0\1\27\17\0\1\27\3\0\4\27\1\64"+
    "\11\27\1\65\12\27\1\0\1\27\17\0\1\27\3\0"+
    "\13\27\1\66\1\27\1\67\10\27\1\70\2\27\1\0"+
    "\1\27\17\0\1\27\3\0\10\27\1\71\2\27\1\72"+
    "\2\27\1\73\12\27\1\0\1\27\1\74\16\0\1\27"+
    "\3\0\16\27\1\75\12\27\1\0\1\27\17\0\1\27"+
    "\3\0\31\27\1\0\1\27\17\0\1\27\3\0\5\27"+
    "\1\76\6\27\1\77\1\100\13\27\1\0\1\27\17\0"+
    "\1\27\3\0\16\27\1\101\12\27\1\0\1\27\17\0"+
    "\1\27\3\0\1\102\3\27\1\103\24\27\1\0\1\27"+
    "\17\0\1\27\3\0\1\104\17\27\1\105\2\27\1\106"+
    "\5\27\1\0\1\27\17\0\1\27\3\0\4\27\1\107"+
    "\24\27\1\0\1\27\17\0\1\27\3\0\7\27\1\110"+
    "\12\27\1\111\1\112\1\27\1\113\1\27\1\114\1\27"+
    "\1\0\1\27\17\0\1\27\3\0\7\27\1\115\10\27"+
    "\1\116\10\27\1\0\1\27\17\0\1\27\3\0\16\27"+
    "\1\117\12\27\1\0\1\27\17\0\1\27\3\0\7\27"+
    "\1\120\21\27\1\0\1\27\30\0\1\10\6\0\1\121"+
    "\1\122\47\0\1\123\12\0\1\124\1\125\1\0\1\126"+
    "\1\0\1\127\7\0\2\130\1\0\1\130\1\44\60\0"+
    "\1\131\45\0\2\51\1\43\1\51\1\5\51\51\14\0"+
    "\1\27\3\0\21\27\1\132\7\27\1\0\1\27\1\0"+
    "\1\133\15\0\1\27\3\0\21\27\1\134\7\27\1\0"+
    "\1\27\1\0\1\135\42\0\1\135\12\0\1\135\15\0"+
    "\1\27\3\0\16\27\1\136\12\27\1\0\1\27\17\0"+
    "\1\27\3\0\4\27\1\137\24\27\1\0\1\27\17\0"+
    "\1\27\3\0\22\27\1\140\6\27\1\0\1\27\17\0"+
    "\1\27\3\0\21\27\1\140\1\141\6\27\1\0\1\27"+
    "\1\0\1\142\15\0\1\27\3\0\1\73\30\27\1\0"+
    "\1\27\17\0\1\27\3\0\1\143\3\27\1\144\24\27"+
    "\1\0\1\27\17\0\1\27\3\0\15\27\1\145\13\27"+
    "\1\0\1\27\17\0\1\27\3\0\5\27\1\146\23\27"+
    "\1\0\1\27\17\0\1\27\3\0\23\27\1\147\5\27"+
    "\1\0\1\27\17\0\1\27\3\0\21\27\1\140\7\27"+
    "\1\0\1\27\1\0\1\142\15\0\1\27\3\0\23\27"+
    "\1\150\5\27\1\0\1\27\17\0\1\27\3\0\22\27"+
    "\1\151\6\27\1\0\1\27\17\0\1\27\3\0\15\27"+
    "\1\152\13\27\1\0\1\27\17\0\1\27\3\0\16\27"+
    "\1\153\12\27\1\0\1\27\17\0\1\27\3\0\20\27"+
    "\1\76\10\27\1\0\1\27\40\0\1\154\34\0\1\27"+
    "\3\0\22\27\1\155\6\27\1\0\1\27\17\0\1\27"+
    "\3\0\17\27\1\156\11\27\1\0\1\27\17\0\1\27"+
    "\3\0\21\27\1\157\1\160\1\161\5\27\1\0\1\27"+
    "\1\0\1\162\15\0\1\27\3\0\15\27\1\163\13\27"+
    "\1\0\1\27\17\0\1\27\3\0\22\27\1\164\6\27"+
    "\1\0\1\27\17\0\1\27\3\0\25\27\1\76\3\27"+
    "\1\0\1\27\17\0\1\27\3\0\2\27\1\165\26\27"+
    "\1\0\1\27\17\0\1\27\3\0\10\27\1\166\5\27"+
    "\1\167\12\27\1\0\1\27\1\170\16\0\1\27\3\0"+
    "\1\27\1\171\27\27\1\0\1\27\17\0\1\27\3\0"+
    "\22\27\1\172\6\27\1\0\1\27\17\0\1\27\3\0"+
    "\16\27\1\173\12\27\1\0\1\27\17\0\1\27\3\0"+
    "\1\174\17\27\1\175\10\27\1\0\1\27\17\0\1\27"+
    "\3\0\17\27\1\176\11\27\1\0\1\27\17\0\1\27"+
    "\3\0\10\27\1\177\20\27\1\0\1\27\1\200\16\0"+
    "\1\27\3\0\15\27\1\201\13\27\1\0\1\27\17\0"+
    "\1\27\3\0\10\27\1\202\7\27\1\203\10\27\1\0"+
    "\1\27\1\204\16\0\1\27\3\0\1\205\26\27\1\76"+
    "\1\27\1\0\1\27\17\0\1\27\3\0\10\27\1\206"+
    "\2\27\1\207\15\27\1\0\1\27\1\210\16\0\1\27"+
    "\3\0\10\27\1\211\20\27\1\0\1\27\1\212\41\0"+
    "\1\213\57\0\1\162\1\214\1\215\10\0\1\162\37\0"+
    "\1\216\37\0\1\217\17\0\1\220\54\0\1\221\46\0"+
    "\1\200\22\0\1\200\37\0\1\222\21\0\2\130\1\0"+
    "\1\130\44\0\1\44\4\0\10\223\1\131\2\223\1\0"+
    "\42\223\14\0\1\27\3\0\22\27\1\224\6\27\1\0"+
    "\1\27\45\0\1\225\27\0\1\27\3\0\4\27\1\173"+
    "\24\27\1\0\1\27\27\0\1\216\45\0\1\27\3\0"+
    "\13\27\1\226\15\27\1\0\1\27\17\0\1\27\3\0"+
    "\1\227\30\27\1\0\1\27\17\0\1\27\3\0\4\27"+
    "\1\76\24\27\1\0\1\27\17\0\1\27\3\0\2\27"+
    "\1\230\26\27\1\0\1\27\27\0\1\10\45\0\1\27"+
    "\3\0\21\27\1\202\7\27\1\0\1\27\1\0\1\204"+
    "\15\0\1\27\3\0\1\231\30\27\1\0\1\27\17\0"+
    "\1\27\3\0\21\27\1\232\1\233\6\27\1\0\1\27"+
    "\1\0\1\234\15\0\1\27\3\0\1\235\30\27\1\0"+
    "\1\27\17\0\1\27\3\0\1\27\1\211\27\27\1\0"+
    "\1\27\17\0\1\27\3\0\14\27\1\76\14\27\1\0"+
    "\1\27\17\0\1\27\3\0\4\27\1\236\24\27\1\0"+
    "\1\27\17\0\1\27\3\0\1\237\30\27\1\0\1\27"+
    "\17\0\1\27\3\0\1\232\30\27\1\0\1\27\23\0"+
    "\1\240\51\0\1\27\3\0\16\27\1\76\12\27\1\0"+
    "\1\27\17\0\1\27\3\0\13\27\1\241\2\27\1\173"+
    "\12\27\1\0\1\27\17\0\1\27\3\0\22\27\1\242"+
    "\6\27\1\0\1\27\17\0\1\27\3\0\4\27\1\243"+
    "\24\27\1\0\1\27\17\0\1\27\3\0\14\27\1\244"+
    "\14\27\1\0\1\27\45\0\1\245\27\0\1\27\3\0"+
    "\6\27\1\76\22\27\1\0\1\27\17\0\1\27\3\0"+
    "\10\27\1\246\20\27\1\0\1\27\1\247\16\0\1\27"+
    "\3\0\12\27\1\250\16\27\1\0\1\27\2\0\1\251"+
    "\14\0\1\27\3\0\15\27\1\252\6\27\1\253\4\27"+
    "\1\0\1\27\17\0\1\27\3\0\22\27\1\254\6\27"+
    "\1\0\1\27\40\0\1\255\6\0\1\256\25\0\1\27"+
    "\3\0\13\27\1\257\15\27\1\0\1\27\17\0\1\27"+
    "\3\0\23\27\1\260\5\27\1\0\1\27\17\0\1\27"+
    "\3\0\20\27\1\232\10\27\1\0\1\27\17\0\1\27"+
    "\3\0\22\27\1\257\6\27\1\0\1\27\17\0\1\27"+
    "\3\0\10\27\1\261\20\27\1\0\1\27\1\262\16\0"+
    "\1\27\3\0\4\27\1\73\24\27\1\0\1\27\17\0"+
    "\1\27\3\0\22\27\1\141\6\27\1\0\1\27\45\0"+
    "\1\263\27\0\1\27\3\0\2\27\1\264\26\27\1\0"+
    "\1\27\17\0\1\27\3\0\21\27\1\76\7\27\1\0"+
    "\1\27\1\0\1\10\15\0\1\27\3\0\16\27\1\265"+
    "\12\27\1\0\1\27\44\0\1\10\12\0\1\10\15\0"+
    "\1\27\3\0\15\27\1\266\13\27\1\0\1\27\17\0"+
    "\1\27\3\0\3\27\1\76\25\27\1\0\1\27\17\0"+
    "\1\27\3\0\1\267\30\27\1\0\1\27\26\0\1\10"+
    "\46\0\1\27\3\0\13\27\1\140\15\27\1\0\1\27"+
    "\36\0\1\142\55\0\1\270\2\0\1\216\43\0\1\271"+
    "\65\0\1\272\61\0\1\234\57\0\1\273\43\0\1\262"+
    "\22\0\1\262\26\0\1\274\53\0\1\275\33\0\10\223"+
    "\1\276\45\223\14\0\1\27\3\0\20\27\1\277\10\27"+
    "\1\0\1\27\43\0\1\300\31\0\1\27\3\0\4\27"+
    "\1\301\24\27\1\0\1\27\17\0\1\27\3\0\12\27"+
    "\1\76\16\27\1\0\1\27\2\0\1\10\14\0\1\27"+
    "\3\0\7\27\1\76\21\27\1\0\1\27\17\0\1\27"+
    "\3\0\20\27\1\302\10\27\1\0\1\27\17\0\1\27"+
    "\3\0\22\27\1\76\6\27\1\0\1\27\17\0\1\27"+
    "\3\0\10\27\1\303\20\27\1\0\1\27\1\304\44\0"+
    "\1\10\27\0\1\27\3\0\23\27\1\305\5\27\1\0"+
    "\1\27\17\0\1\27\3\0\15\27\1\306\13\27\1\0"+
    "\1\27\17\0\1\27\3\0\13\27\1\307\15\27\1\0"+
    "\1\27\36\0\1\310\36\0\1\27\3\0\4\27\1\311"+
    "\24\27\1\0\1\27\17\0\1\27\3\0\1\312\30\27"+
    "\1\0\1\27\17\0\1\27\3\0\20\27\1\313\10\27"+
    "\1\0\1\27\17\0\1\27\3\0\1\27\1\314\27\27"+
    "\1\0\1\27\23\0\1\315\51\0\1\27\3\0\24\27"+
    "\1\140\4\27\1\0\1\27\47\0\1\142\25\0\1\27"+
    "\3\0\1\316\30\27\1\0\1\27\23\0\1\317\51\0"+
    "\1\27\3\0\22\27\1\320\6\27\1\0\1\27\17\0"+
    "\1\27\3\0\1\57\30\27\1\0\1\27\17\0\1\27"+
    "\3\0\4\27\1\321\24\27\1\0\1\27\45\0\1\322"+
    "\33\0\1\323\51\0\1\27\3\0\10\27\1\324\20\27"+
    "\1\0\1\27\1\325\16\0\1\27\3\0\20\27\1\326"+
    "\10\27\1\0\1\27\17\0\1\27\3\0\2\27\1\327"+
    "\26\27\1\0\1\27\25\0\1\330\55\0\1\331\47\0"+
    "\1\27\3\0\7\27\1\332\21\27\1\0\1\27\17\0"+
    "\1\27\3\0\25\27\1\333\3\27\1\0\1\27\17\0"+
    "\1\27\3\0\21\27\1\334\7\27\1\0\1\27\1\0"+
    "\1\335\15\0\1\27\3\0\22\27\1\120\6\27\1\0"+
    "\1\27\27\0\1\336\71\0\1\337\36\0\1\340\64\0"+
    "\1\325\22\0\1\325\42\0\1\10\44\0\1\341\26\0"+
    "\10\223\1\276\2\223\1\43\42\223\14\0\1\27\3\0"+
    "\1\342\30\27\1\0\1\27\23\0\1\343\51\0\1\27"+
    "\3\0\1\326\30\27\1\0\1\27\17\0\1\27\3\0"+
    "\15\27\1\344\13\27\1\0\1\27\40\0\1\345\34\0"+
    "\1\27\3\0\13\27\1\232\15\27\1\0\1\27\17\0"+
    "\1\27\3\0\3\27\1\202\25\27\1\0\1\27\17\0"+
    "\1\27\3\0\13\27\1\346\15\27\1\0\1\27\36\0"+
    "\1\347\36\0\1\27\3\0\14\27\1\350\14\27\1\0"+
    "\1\27\17\0\1\27\3\0\15\27\1\351\13\27\1\0"+
    "\1\27\17\0\1\27\3\0\5\27\1\352\23\27\1\0"+
    "\1\27\17\0\1\27\3\0\4\27\1\231\24\27\1\0"+
    "\1\27\40\0\1\353\34\0\1\27\3\0\6\27\1\140"+
    "\22\27\1\0\1\27\31\0\1\142\43\0\1\27\3\0"+
    "\13\27\1\354\15\27\1\0\1\27\17\0\1\27\3\0"+
    "\2\27\1\355\26\27\1\0\1\27\36\0\1\356\64\0"+
    "\1\142\27\0\1\27\3\0\2\27\1\76\26\27\1\0"+
    "\1\27\25\0\1\10\47\0\1\27\3\0\15\27\1\76"+
    "\13\27\1\0\1\27\17\0\1\27\3\0\22\27\1\357"+
    "\6\27\1\0\1\27\45\0\1\360\42\0\1\10\42\0"+
    "\1\27\3\0\20\27\1\361\10\27\1\0\1\27\17\0"+
    "\1\27\3\0\10\27\1\362\20\27\1\0\1\27\1\363"+
    "\32\0\1\363\22\0\1\363\36\0\1\364\46\0\1\365"+
    "\54\0\1\366\71\0\1\367\31\0\1\27\3\0\2\27"+
    "\1\232\26\27\1\0\1\27\25\0\1\234\47\0\1\27"+
    "\3\0\23\27\1\140\5\27\1\0\1\27\46\0\1\142"+
    "\26\0\1\27\3\0\27\27\1\76\1\27\1\0\1\27"+
    "\52\0\1\10\22\0\1\27\3\0\4\27\1\370\24\27"+
    "\1\0\1\27\17\0\1\27\3\0\2\27\1\371\26\27"+
    "\1\0\1\27\17\0\1\27\3\0\1\372\30\27\1\0"+
    "\1\27\25\0\1\373\47\0\1\27\3\0\15\27\1\302"+
    "\13\27\1\0\1\27\17\0\1\27\3\0\22\27\1\374"+
    "\6\27\1\0\1\27\40\0\1\375\34\0\1\27\3\0"+
    "\5\27\1\376\23\27\1\0\1\27\30\0\1\377\44\0"+
    "\1\27\3\0\16\27\1\u0100\12\27\1\0\1\27\17\0"+
    "\1\27\3\0\4\27\1\u0101\24\27\1\0\1\27\27\0"+
    "\1\u0102\55\0\1\u0103\51\0\1\u0104\75\0\1\375\53\0"+
    "\1\u0105\33\0\1\27\3\0\15\27\1\u0106\13\27\1\0"+
    "\1\27\17\0\1\27\3\0\4\27\1\u0107\24\27\1\0"+
    "\1\27\17\0\1\27\3\0\2\27\1\140\26\27\1\0"+
    "\1\27\27\0\1\u0108\45\0\1\27\3\0\4\27\1\206"+
    "\24\27\1\0\1\27\17\0\1\27\3\0\17\27\1\76"+
    "\11\27\1\0\1\27\42\0\1\10\32\0\1\27\3\0"+
    "\15\27\1\u0109\13\27\1\0\1\27\17\0\1\27\3\0"+
    "\15\27\1\232\13\27\1\0\1\27\40\0\1\234\55\0"+
    "\1\u010a\42\0\1\142\70\0\1\u010b\34\0\1\27\3\0"+
    "\22\27\1\202\6\27\1\0\1\27\17\0\1\27\3\0"+
    "\16\27\1\u010c\12\27\1\0\1\27\41\0\1\u010d\33\0"+
    "\1\27\3\0\10\27\1\u010e\20\27\1\0\1\27\1\u010f"+
    "\44\0\1\204\43\0\1\u010f\22\0\1\u010f\16\0\1\27"+
    "\3\0\5\27\1\76\23\27\1\0\1\27\30\0\1\10"+
    "\44\0\1\27\3\0\30\27\1\374\1\0\1\27\53\0"+
    "\1\u0110\31\0\1\210\31\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[12006];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\1\11\3\1\2\11\32\1\1\11\1\0"+
    "\1\11\1\0\1\11\2\0\2\1\1\0\17\1\1\0"+
    "\24\1\11\0\1\1\1\0\1\1\1\0\4\1\1\0"+
    "\11\1\1\0\5\1\1\0\5\1\1\0\7\1\1\0"+
    "\3\1\1\0\3\1\1\0\1\1\2\0\1\1\7\0"+
    "\1\1\1\0\6\1\1\0\3\1\1\0\4\1\1\0"+
    "\1\1\1\0\1\1\1\0\3\1\2\0\3\1\2\0"+
    "\4\1\7\0\1\1\1\0\3\1\1\0\10\1\1\0"+
    "\1\1\1\0\2\1\2\0\1\1\1\0\2\1\2\0"+
    "\3\1\5\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\3\1\1\0\2\1\1\0\1\1\1\0\2\1\5\0"+
    "\3\1\1\0\1\1\1\11\1\1\1\0\2\1\4\0"+
    "\2\1\1\0\1\1\2\0\1\1\1\0\1\1\2\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[272];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Yytoken yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Yytoken("Error",yytext(),yyline,yycolumn);
            }
          // fall through
          case 10: break;
          case 2:
            { 
            }
          // fall through
          case 11: break;
          case 3:
          case 8: {
              String Operators = null;
              return new Yytoken("keyword", null,yyline,yycolumn);
            }
          // fall through
          case 12: break;
          case 4:
            { return new Yytoken("keyword",yytext(),yyline,yycolumn);
            }
          // fall through
          case 13: break;
          case 5:
            { return new Yytoken("number",yytext(),yyline,yycolumn);
            }
          // fall through
          case 14: break;
          case 6:
            { return new Yytoken("ident",yytext(),yyline,yycolumn);
            }
          // fall through
          case 15: break;
          case 7:
            { String str =  yytext().substring(1,yylength()-1);
    return new Yytoken("String",str,yyline,yycolumn);
            }
          // fall through
          case 16: break;
          // fall through
          case 17: break;
          case 9:
            { return new Yytoken("reserved",yytext(),yyline,yycolumn);
            }
          // fall through
          case 18: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
