
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LT = 11;
  public static final int SEMICOLON = 5;
  public static final int RBRACE = 3;
  public static final int RPAREN = 7;
  public static final int WHILE = 8;
  public static final int BOOLEAN_LITERAL = 17;
  public static final int IDENTIFIER = 20;
  public static final int IF = 10;
  public static final int LPAREN = 6;
  public static final int GT = 12;
  public static final int LBRACE = 2;
  public static final int STRING_LITERAL = 19;
  public static final int DO = 14;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int FLOATING_POINT_LITERAL = 16;
  public static final int EQ = 13;
  public static final int CHARACTER_LITERAL = 18;
  public static final int INTEGER = 15;
  public static final int FOR = 9;
  public static final int VOID = 4;
  public static final int NULL_LITERAL = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACE",
  "RBRACE",
  "VOID",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "WHILE",
  "FOR",
  "IF",
  "LT",
  "GT",
  "EQ",
  "DO",
  "INTEGER",
  "FLOATING_POINT_LITERAL",
  "BOOLEAN_LITERAL",
  "CHARACTER_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "NULL_LITERAL"
  };
}

